import type {
  Artifact,
  AskSession,
  Claim,
  CompileJob,
  Contradiction,
  EvidenceLink,
  Project,
  Source,
  SourceFragment,
  TimelineEvent,
  WikiPage,
  WikiPageRevision,
  WikiPageSourceLink,
} from "@/lib/domain/types";
import { parseSourceFragments } from "@/lib/domain/source-fragment-parser";

export const activeProjectId = "project-eregionforge";

export const seedProjects: Project[] = [
  {
    id: "project-eregionforge",
    ownerId: null,
    slug: "eregionforge",
    name: "EregionForge",
    description:
      "Product and architecture workspace for building a knowledge compiler centered on canonical wiki pages, evidence, and durable artifacts.",
    domain: "Product systems research",
    status: "active",
    createdAt: "2026-04-03T00:00:00Z",
    updatedAt: "2026-04-03T00:00:00Z",
  },
  {
    id: "project-northstar-semiconductor",
    ownerId: null,
    slug: "northstar-semiconductor-diligence",
    name: "Northstar Semiconductor Diligence",
    description:
      "Internal diligence workspace assessing a power semiconductor supplier across market structure, unit economics, and execution risk.",
    domain: "Investment research",
    status: "active",
    createdAt: "2026-04-02T18:20:00Z",
    updatedAt: "2026-04-03T00:00:00Z",
  },
];

export const seedSources: Source[] = [
  {
    id: "source-ef-readme",
    projectId: "project-eregionforge",
    sourceType: "markdown",
    title: "README.md",
    body: "Defines EregionForge as an agentic knowledge compiler rather than a chat-with-files product.",
    url: null,
    filePath: "README.md",
    status: "compiled",
    provenance: { label: "Repository root", kind: "repo-file" },
    metadata: { layer: "product", format: "markdown" },
    createdAt: "2026-04-03T00:00:00Z",
    updatedAt: "2026-04-03T00:00:00Z",
  },
  {
    id: "source-ef-vision",
    projectId: "project-eregionforge",
    sourceType: "markdown",
    title: "Product Vision",
    body: "Explains the promise of turning source chaos into a living research wiki.",
    url: null,
    filePath: "docs/product/vision.md",
    status: "compiled",
    provenance: { label: "docs/product/vision.md", kind: "repo-file" },
    metadata: { layer: "product", format: "markdown" },
    createdAt: "2026-04-03T00:00:00Z",
    updatedAt: "2026-04-03T00:00:00Z",
  },
  {
    id: "source-ef-mvp",
    projectId: "project-eregionforge",
    sourceType: "markdown",
    title: "MVP Scope",
    body: "Defines the first product loop from project creation through artifacts.",
    url: null,
    filePath: "docs/product/mvp-scope.md",
    status: "extracted",
    provenance: { label: "docs/product/mvp-scope.md", kind: "repo-file" },
    metadata: { layer: "product", format: "markdown" },
    createdAt: "2026-04-03T00:00:00Z",
    updatedAt: "2026-04-03T00:00:00Z",
  },
  {
    id: "source-ef-architecture",
    projectId: "project-eregionforge",
    sourceType: "markdown",
    title: "System Architecture",
    body: "Defines interface, services, data, and agent layers for durable knowledge compilation.",
    url: null,
    filePath: "docs/architecture/system-architecture.md",
    status: "compiled",
    provenance: {
      label: "docs/architecture/system-architecture.md",
      kind: "repo-file",
    },
    metadata: { layer: "architecture", format: "markdown" },
    createdAt: "2026-04-03T00:00:00Z",
    updatedAt: "2026-04-03T00:00:00Z",
  },
  {
    id: "source-ef-data-model",
    projectId: "project-eregionforge",
    sourceType: "markdown",
    title: "Data Model Overview",
    body: "Lists the layered knowledge model from raw sources through artifacts.",
    url: null,
    filePath: "docs/architecture/data-model.md",
    status: "extracted",
    provenance: { label: "docs/architecture/data-model.md", kind: "repo-file" },
    metadata: { layer: "architecture", format: "markdown" },
    createdAt: "2026-04-03T00:00:00Z",
    updatedAt: "2026-04-03T00:00:00Z",
  },
  {
    id: "source-ef-roadmap",
    projectId: "project-eregionforge",
    sourceType: "markdown",
    title: "Master Roadmap",
    body: "Sequences the program from shell and schema through compilation and hardening.",
    url: null,
    filePath: "docs/sprints/00-master-roadmap.md",
    status: "parsed",
    provenance: { label: "docs/sprints/00-master-roadmap.md", kind: "repo-file" },
    metadata: { layer: "delivery", format: "markdown" },
    createdAt: "2026-04-03T00:00:00Z",
    updatedAt: "2026-04-03T00:00:00Z",
  },
  {
    id: "source-ef-ask-direction-note",
    projectId: "project-eregionforge",
    sourceType: "markdown",
    title: "Early Ask Direction Note",
    body: "An early proposal suggested EregionForge should act as a broad conversational assistant over raw files before canonical wiki compilation exists.",
    url: null,
    filePath: "docs/product/ask-direction-note.md",
    status: "parsed",
    provenance: { label: "docs/product/ask-direction-note.md", kind: "repo-file" },
    metadata: { layer: "product", format: "markdown", status: "superseded-note" },
    createdAt: "2026-04-03T00:00:00Z",
    updatedAt: "2026-04-03T00:00:00Z",
  },
  {
    id: "source-ef-schema",
    projectId: "project-eregionforge",
    sourceType: "text",
    title: "Schema Blueprint",
    body: "Initial Supabase schema for projects, sources, wiki pages, revisions, claims, evidence, artifacts, jobs, and ask sessions.",
    url: null,
    filePath: "supabase/schema.sql",
    status: "parsed",
    provenance: { label: "supabase/schema.sql", kind: "repo-file" },
    metadata: { layer: "data", format: "sql" },
    createdAt: "2026-04-03T00:00:00Z",
    updatedAt: "2026-04-03T00:00:00Z",
  },
  {
    id: "source-ns-investor-day",
    projectId: "project-northstar-semiconductor",
    sourceType: "pdf",
    title: "FY2025 Investor Day Deck",
    body: "Management frames gross margin expansion around power module mix and automotive design wins.",
    url: "https://example.com/northstar-investor-day.pdf",
    filePath: null,
    status: "parsed",
    provenance: { label: "Investor relations", kind: "url" },
    metadata: { issuer: "Northstar Semi", period: "FY2025" },
    createdAt: "2026-04-02T18:20:00Z",
    updatedAt: "2026-04-02T18:20:00Z",
  },
  {
    id: "source-ns-earnings-call",
    projectId: "project-northstar-semiconductor",
    sourceType: "text",
    title: "Q4 2025 Earnings Call Transcript",
    body: "Management comments on utilization, pricing discipline, and backlog normalization.",
    url: "https://example.com/northstar-q4-transcript",
    filePath: null,
    status: "compiled",
    provenance: { label: "Transcript provider", kind: "url" },
    metadata: { issuer: "Northstar Semi", period: "Q4 2025" },
    createdAt: "2026-04-02T19:10:00Z",
    updatedAt: "2026-04-02T19:10:00Z",
  },
  {
    id: "source-ns-channel-checks",
    projectId: "project-northstar-semiconductor",
    sourceType: "markdown",
    title: "Channel Check Notes: EV Power Modules",
    body: "Distributor conversations suggest lead times have normalized but automotive qualification remains sticky.",
    url: null,
    filePath: "research/channel-checks/ev-power-modules.md",
    status: "compiled",
    provenance: { label: "Internal research note", kind: "workspace-note" },
    metadata: { sourceClass: "field-research", region: "North America" },
    createdAt: "2026-04-02T20:45:00Z",
    updatedAt: "2026-04-02T20:45:00Z",
  },
  {
    id: "source-ns-pricing-table",
    projectId: "project-northstar-semiconductor",
    sourceType: "markdown",
    title: "Competitor Pricing Table",
    body: "Side-by-side pricing and package comparison across four power module vendors.",
    url: null,
    filePath: "research/pricing/competitor-table.md",
    status: "extracted",
    provenance: { label: "Internal comp sheet", kind: "workspace-note" },
    metadata: { coverage: "pricing", comparatorSet: "power modules" },
    createdAt: "2026-04-02T21:00:00Z",
    updatedAt: "2026-04-02T21:00:00Z",
  },
  {
    id: "source-ns-industry-note",
    projectId: "project-northstar-semiconductor",
    sourceType: "markdown",
    title: "Wide-Bandgap Adoption Note",
    body: "Industry note on silicon carbide adoption pacing, capacity additions, and expected ASP compression.",
    url: null,
    filePath: "research/industry/wide-bandgap-adoption.md",
    status: "failed",
    provenance: { label: "Internal industry note", kind: "workspace-note" },
    metadata: { theme: "SiC adoption", region: "Global" },
    createdAt: "2026-04-02T22:15:00Z",
    updatedAt: "2026-04-02T22:15:00Z",
  },
];

export const seedSourceFragments: SourceFragment[] = seedSources.flatMap((source) =>
  parseSourceFragments(source).map((fragment) => ({
    ...fragment,
    id: `${source.id}-fragment-${String(fragment.index + 1).padStart(2, "0")}`,
    createdAt: source.createdAt,
    updatedAt: source.updatedAt,
  })),
);

export const seedClaims: Claim[] = [];

export const seedEvidenceLinks: EvidenceLink[] = [];

export const seedWikiPages: WikiPage[] = [
  {
    id: "page-ef-overview",
    projectId: "project-eregionforge",
    slug: "overview",
    title: "Overview",
    pageType: "overview",
    currentRevisionId: "revision-ef-overview-r1",
    status: "active",
    createdAt: "2026-04-03T00:00:00Z",
    updatedAt: "2026-04-03T00:00:00Z",
  },
  {
    id: "page-ef-scope",
    projectId: "project-eregionforge",
    slug: "mvp-scope",
    title: "MVP Scope",
    pageType: "scope",
    currentRevisionId: "revision-ef-scope-r1",
    status: "active",
    createdAt: "2026-04-03T00:00:00Z",
    updatedAt: "2026-04-03T00:00:00Z",
  },
  {
    id: "page-ef-architecture",
    projectId: "project-eregionforge",
    slug: "system-architecture",
    title: "System Architecture",
    pageType: "architecture",
    currentRevisionId: "revision-ef-architecture-r1",
    status: "active",
    createdAt: "2026-04-03T00:00:00Z",
    updatedAt: "2026-04-03T00:00:00Z",
  },
  {
    id: "page-ef-data-model",
    projectId: "project-eregionforge",
    slug: "data-model",
    title: "Data Model",
    pageType: "data-model",
    currentRevisionId: "revision-ef-data-model-r1",
    status: "draft",
    createdAt: "2026-04-03T00:00:00Z",
    updatedAt: "2026-04-03T00:00:00Z",
  },
  {
    id: "page-ef-roadmap",
    projectId: "project-eregionforge",
    slug: "roadmap",
    title: "Sprint Roadmap",
    pageType: "roadmap",
    currentRevisionId: "revision-ef-roadmap-r1",
    status: "active",
    createdAt: "2026-04-03T00:00:00Z",
    updatedAt: "2026-04-03T00:00:00Z",
  },
  {
    id: "page-ef-open-questions",
    projectId: "project-eregionforge",
    slug: "open-questions",
    title: "Open Questions",
    pageType: "open-questions",
    currentRevisionId: "revision-ef-open-questions-r1",
    status: "draft",
    createdAt: "2026-04-03T00:00:00Z",
    updatedAt: "2026-04-03T00:00:00Z",
  },
  {
    id: "page-ns-dossier",
    projectId: "project-northstar-semiconductor",
    slug: "company-overview",
    title: "Company Overview",
    pageType: "dossier",
    currentRevisionId: "revision-ns-dossier-r1",
    status: "active",
    createdAt: "2026-04-02T18:20:00Z",
    updatedAt: "2026-04-02T18:20:00Z",
  },
  {
    id: "page-ns-thesis",
    projectId: "project-northstar-semiconductor",
    slug: "investment-thesis",
    title: "Investment Thesis",
    pageType: "investment-thesis",
    currentRevisionId: "revision-ns-thesis-r1",
    status: "active",
    createdAt: "2026-04-02T18:20:00Z",
    updatedAt: "2026-04-02T18:20:00Z",
  },
  {
    id: "page-ns-market",
    projectId: "project-northstar-semiconductor",
    slug: "market-structure",
    title: "Market Structure",
    pageType: "market-map",
    currentRevisionId: "revision-ns-market-r1",
    status: "active",
    createdAt: "2026-04-02T18:20:00Z",
    updatedAt: "2026-04-02T18:20:00Z",
  },
  {
    id: "page-ns-risks",
    projectId: "project-northstar-semiconductor",
    slug: "risk-register",
    title: "Risk Register",
    pageType: "risk-register",
    currentRevisionId: "revision-ns-risks-r1",
    status: "active",
    createdAt: "2026-04-02T18:20:00Z",
    updatedAt: "2026-04-02T18:20:00Z",
  },
  {
    id: "page-ns-open-questions",
    projectId: "project-northstar-semiconductor",
    slug: "open-questions",
    title: "Open Questions",
    pageType: "open-questions",
    currentRevisionId: "revision-ns-open-questions-r1",
    status: "draft",
    createdAt: "2026-04-02T18:20:00Z",
    updatedAt: "2026-04-02T18:20:00Z",
  },
];

export const seedWikiPageRevisions: WikiPageRevision[] = [
  {
    id: "revision-ef-overview-r1",
    pageId: "page-ef-overview",
    markdownContent: "# Overview\nEregionForge compiles raw sources into canonical wiki pages and durable research artifacts.",
    summary:
      "Frames the product around a canonical, auditable research wiki rather than ephemeral answers.",
    changeNote: "Initial seeded canon from README and vision.",
    confidence: "high",
    createdBy: "system",
    createdAt: "2026-04-03T00:02:00Z",
  },
  {
    id: "revision-ef-scope-r1",
    pageId: "page-ef-scope",
    markdownContent: "# MVP Scope\nCreate project, add sources, compile wiki, ask against canon, and save artifacts.",
    summary:
      "Captures the minimum loop that proves the knowledge compiler works.",
    changeNote: "Initial scope capture from MVP doc.",
    confidence: "high",
    createdBy: "system",
    createdAt: "2026-04-03T00:03:00Z",
  },
  {
    id: "revision-ef-architecture-r1",
    pageId: "page-ef-architecture",
    markdownContent: "# Architecture\nInterface, services, data, and agent layers are separated cleanly.",
    summary:
      "Maps the application shell to service boundaries and durable-object persistence.",
    changeNote: "Initial architecture synthesis.",
    confidence: "high",
    createdBy: "system",
    createdAt: "2026-04-03T00:04:00Z",
  },
  {
    id: "revision-ef-data-model-r1",
    pageId: "page-ef-data-model",
    markdownContent: "# Data Model\nProjects, sources, wiki pages, revisions, claims, evidence, and artifacts form the core domain.",
    summary:
      "Bridges the conceptual data model to the schema blueprint and identifies missing app wiring.",
    changeNote: "Seeded from data model doc and schema blueprint.",
    confidence: "medium",
    createdBy: "system",
    createdAt: "2026-04-03T00:05:00Z",
  },
  {
    id: "revision-ef-roadmap-r1",
    pageId: "page-ef-roadmap",
    markdownContent: "# Roadmap\nShell, schema, ingestion, compilation, evidence, ask, artifacts, and hardening.",
    summary:
      "Documents the implementation order required to make the wiki central before richer workflows land.",
    changeNote: "Roadmap seeded from sprint documents.",
    confidence: "high",
    createdBy: "system",
    createdAt: "2026-04-03T00:06:00Z",
  },
  {
    id: "revision-ef-open-questions-r1",
    pageId: "page-ef-open-questions",
    markdownContent: "# Open Questions\nHow should active project routing evolve once persistence lands?",
    summary:
      "Tracks open decisions around project scoping, first compile triggers, and evidence surfacing.",
    changeNote: "Initial gaps identified during shell implementation.",
    confidence: "medium",
    createdBy: "system",
    createdAt: "2026-04-03T00:07:00Z",
  },
  {
    id: "revision-ns-dossier-r1",
    pageId: "page-ns-dossier",
    markdownContent: "# Company Overview\nNorthstar is a focused supplier of power modules with automotive and industrial exposure.",
    summary:
      "Establishes the company profile, product mix, and end-market exposure for diligence work.",
    changeNote: "Seeded from investor day and transcript.",
    confidence: "high",
    createdBy: "system",
    createdAt: "2026-04-02T22:20:00Z",
  },
  {
    id: "revision-ns-thesis-r1",
    pageId: "page-ns-thesis",
    markdownContent: "# Investment Thesis\nUpside depends on mix improvement, disciplined pricing, and stable auto qualification wins.",
    summary:
      "Frames the long case around margin expansion and customer stickiness while preserving execution caution.",
    changeNote: "Initial thesis assembly from management and channel data.",
    confidence: "medium",
    createdBy: "researcher",
    createdAt: "2026-04-02T22:35:00Z",
  },
  {
    id: "revision-ns-market-r1",
    pageId: "page-ns-market",
    markdownContent: "# Market Structure\nWide-bandgap adoption expands the TAM, but pricing pressure can compress returns.",
    summary:
      "Maps the competitive set, pricing posture, and adoption curves shaping the diligence case.",
    changeNote: "Built from pricing table and industry note.",
    confidence: "medium",
    createdBy: "compiler",
    createdAt: "2026-04-02T22:45:00Z",
  },
  {
    id: "revision-ns-risks-r1",
    pageId: "page-ns-risks",
    markdownContent: "# Risk Register\nNormalization, ASP pressure, and utilization swings remain the primary downside vectors.",
    summary:
      "Captures the execution and cycle risks that could break the underwriting case.",
    changeNote: "Risk register seeded from transcript and field notes.",
    confidence: "high",
    createdBy: "compiler",
    createdAt: "2026-04-02T22:50:00Z",
  },
  {
    id: "revision-ns-open-questions-r1",
    pageId: "page-ns-open-questions",
    markdownContent: "# Open Questions\nHow durable is Northstar's pricing versus the next 12 months of industry capacity additions?",
    summary:
      "Lists diligence questions still requiring primary research and model work.",
    changeNote: "Initial open questions set.",
    confidence: "medium",
    createdBy: "researcher",
    createdAt: "2026-04-02T22:55:00Z",
  },
];

export const seedArtifacts: Artifact[] = [
  {
    id: "artifact-ef-shell-brief",
    projectId: "project-eregionforge",
    artifactType: "memo",
    title: "Sprint 2 Domain Wiring Brief",
    markdownContent: "Domain types, repositories, and project-aware workspace seams are now in place.",
    previewText:
      "Domain types, repositories, and project-aware workspace seams are now in place.",
    provenance: "research-synthesis",
    originatingPrompt: null,
    derivedFromAskSessionId: null,
    referencedWikiPageIds: ["page-ef-data-model", "page-ef-architecture"],
    referencedSourceIds: ["source-ef-data-model", "source-ef-architecture"],
    referencedClaimIds: [],
    eligibleForWikiFiling: true,
    status: "draft",
    metadata: { derivedFrom: "Data Model, System Architecture" },
    createdAt: "2026-04-03T00:20:00Z",
    updatedAt: "2026-04-03T00:20:00Z",
  },
  {
    id: "artifact-ef-execution-brief",
    projectId: "project-eregionforge",
    artifactType: "briefing",
    title: "MVP Execution Brief",
    markdownContent: "Schema wiring, source ingestion, and wiki compilation should precede ask and artifact automation.",
    previewText:
      "Schema wiring, source ingestion, and wiki compilation should precede ask and artifact automation.",
    provenance: "wiki-derived",
    originatingPrompt: null,
    derivedFromAskSessionId: null,
    referencedWikiPageIds: ["page-ef-roadmap"],
    referencedSourceIds: ["source-ef-roadmap"],
    referencedClaimIds: [],
    eligibleForWikiFiling: true,
    status: "active",
    metadata: { derivedFrom: "Sprint Roadmap" },
    createdAt: "2026-04-03T00:16:00Z",
    updatedAt: "2026-04-03T00:16:00Z",
  },
  {
    id: "artifact-ef-adr",
    projectId: "project-eregionforge",
    artifactType: "memo",
    title: "Architecture Decision: Canon First",
    markdownContent: "The compiled wiki remains the source of truth for downstream ask and artifact flows.",
    previewText:
      "The compiled wiki remains the source of truth for downstream ask and artifact flows.",
    provenance: "wiki-derived",
    originatingPrompt: null,
    derivedFromAskSessionId: null,
    referencedWikiPageIds: ["page-ef-overview", "page-ef-architecture"],
    referencedSourceIds: ["source-ef-readme", "source-ef-architecture"],
    referencedClaimIds: [],
    eligibleForWikiFiling: true,
    status: "active",
    metadata: { derivedFrom: "Overview, System Architecture" },
    createdAt: "2026-04-03T00:18:00Z",
    updatedAt: "2026-04-03T00:18:00Z",
  },
  {
    id: "artifact-ns-diligence-memo",
    projectId: "project-northstar-semiconductor",
    artifactType: "saved_answer",
    title: "Initial Diligence Memo",
    markdownContent: "Northstar screens interesting on mix but still needs deeper work on pricing durability.",
    previewText:
      "Northstar screens interesting on mix but still needs deeper work on pricing durability.",
    provenance: "research-synthesis",
    originatingPrompt: null,
    derivedFromAskSessionId: null,
    referencedWikiPageIds: ["page-ns-thesis", "page-ns-risks"],
    referencedSourceIds: ["source-ns-investor-day", "source-ns-earnings-call"],
    referencedClaimIds: [],
    eligibleForWikiFiling: false,
    status: "active",
    metadata: { derivedFrom: "Investment Thesis, Risk Register" },
    createdAt: "2026-04-02T23:10:00Z",
    updatedAt: "2026-04-02T23:10:00Z",
  },
  {
    id: "artifact-ns-comparison",
    projectId: "project-northstar-semiconductor",
    artifactType: "comparison_report",
    title: "Competitive Pricing Snapshot",
    markdownContent: "Benchmarking shows Northstar premium pricing holds in automotive modules but not in industrial sockets.",
    previewText:
      "Benchmarking shows Northstar premium pricing holds in automotive modules but not in industrial sockets.",
    provenance: "research-synthesis",
    originatingPrompt: null,
    derivedFromAskSessionId: null,
    referencedWikiPageIds: ["page-ns-market"],
    referencedSourceIds: ["source-ns-pricing-table"],
    referencedClaimIds: [],
    eligibleForWikiFiling: true,
    status: "draft",
    metadata: { derivedFrom: "Market Structure" },
    createdAt: "2026-04-02T23:25:00Z",
    updatedAt: "2026-04-02T23:25:00Z",
  },
  {
    id: "artifact-ns-follow-ups",
    projectId: "project-northstar-semiconductor",
    artifactType: "briefing",
    title: "IC Follow-up Agenda",
    markdownContent: "Further channel checks and model validation needed before sizing conviction.",
    previewText:
      "Further channel checks and model validation needed before sizing conviction.",
    provenance: "research-synthesis",
    originatingPrompt: null,
    derivedFromAskSessionId: null,
    referencedWikiPageIds: ["page-ns-open-questions"],
    referencedSourceIds: ["source-ns-channel-checks"],
    referencedClaimIds: [],
    eligibleForWikiFiling: false,
    status: "draft",
    metadata: { derivedFrom: "Open Questions" },
    createdAt: "2026-04-02T23:30:00Z",
    updatedAt: "2026-04-02T23:30:00Z",
  },
];

export const seedAskSessions: AskSession[] = [];
export const seedTimelineEvents: TimelineEvent[] = [];
export const seedContradictions: Contradiction[] = [];

export const seedCompileJobs: CompileJob[] = [
  {
    id: "compile-ef-r1",
    projectId: "project-eregionforge",
    status: "completed",
    triggeredBy: "seed-system",
    summary:
      "Initial seeded compile established canonical product pages from repository planning documents.",
    affectedPageIds: [
      "page-ef-overview",
      "page-ef-scope",
      "page-ef-architecture",
      "page-ef-data-model",
      "page-ef-roadmap",
      "page-ef-open-questions",
    ],
    sourceCount: 8,
    metadata: { trigger: "seeded from repo docs" },
    startedAt: "2026-04-03T00:01:00Z",
    completedAt: "2026-04-03T00:07:00Z",
    createdAt: "2026-04-03T00:01:00Z",
  },
  {
    id: "compile-ns-r1",
    projectId: "project-northstar-semiconductor",
    status: "running",
    triggeredBy: "seed-system",
    summary:
      "Incremental diligence compile is incorporating a new industry note into the market and risk pages.",
    affectedPageIds: ["page-ns-market", "page-ns-risks", "page-ns-open-questions"],
    sourceCount: 5,
    metadata: { trigger: "new industry note" },
    startedAt: "2026-04-03T00:10:00Z",
    completedAt: null,
    createdAt: "2026-04-03T00:10:00Z",
  },
];

export const seedWikiPageSourceLinks: WikiPageSourceLink[] = [
  { pageId: "page-ef-overview", sourceId: "source-ef-readme" },
  { pageId: "page-ef-overview", sourceId: "source-ef-vision" },
  { pageId: "page-ef-scope", sourceId: "source-ef-mvp" },
  { pageId: "page-ef-architecture", sourceId: "source-ef-architecture" },
  { pageId: "page-ef-data-model", sourceId: "source-ef-data-model" },
  { pageId: "page-ef-data-model", sourceId: "source-ef-schema" },
  { pageId: "page-ef-roadmap", sourceId: "source-ef-roadmap" },
  { pageId: "page-ef-open-questions", sourceId: "source-ef-schema" },
  { pageId: "page-ef-open-questions", sourceId: "source-ef-architecture" },
  { pageId: "page-ns-dossier", sourceId: "source-ns-investor-day" },
  { pageId: "page-ns-dossier", sourceId: "source-ns-earnings-call" },
  { pageId: "page-ns-thesis", sourceId: "source-ns-investor-day" },
  { pageId: "page-ns-thesis", sourceId: "source-ns-channel-checks" },
  { pageId: "page-ns-market", sourceId: "source-ns-pricing-table" },
  { pageId: "page-ns-market", sourceId: "source-ns-industry-note" },
  { pageId: "page-ns-risks", sourceId: "source-ns-earnings-call" },
  { pageId: "page-ns-risks", sourceId: "source-ns-channel-checks" },
  { pageId: "page-ns-open-questions", sourceId: "source-ns-industry-note" },
];
